json.id resource.id
json.agenda_professional_id resource.agenda_professional_id
json.agenda_event_type_id resource.agenda_event_type_id
json.contact_id resource.contact_id
json.conversation_id resource.conversation_id
json.starts_at resource.starts_at.iso8601
json.ends_at resource.ends_at.iso8601
json.status resource.status
json.rescheduled resource.rescheduled
json.rescheduled_from_id resource.rescheduled_from_id
json.cancelled_at resource.cancelled_at&.iso8601
json.cancellation_reason resource.cancellation_reason
json.source resource.source
json.patient_name resource.patient_name
json.patient_phone resource.patient_phone
json.notes resource.notes
json.created_at resource.created_at.to_i
json.updated_at resource.updated_at.to_i
